### PR TITLE
added support for building on linux

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Tested on Ubuntu 14.04

### CODE REVIEW

**Comment by danrobinson** [comment]
Thanks!

**Comment by TheNeuralBit** [comment]
No problem! I like what you've started here, particularly the pure JS implementation for the browser - anything I can do to help out with that?

**Comment by danrobinson** [comment]
What's your interest in an in-browser implementation? My assumption has been that a Node version will be more useful and should be the priority, particularly because a shared memory format with Java/Python/C++ isn't that useful in the browser. But having an in-browser implementation is definitely part of the dream, so JS libraries that build on JSArrow can at least be used in the browser. (Ambitiously, maybe we could even use PNaCl or WebAssembly for speed.)

If you're just more interested in JS than C++, I definitely am hoping to have more of the logic done in JavaScript even in the Node implementation. The C++ in the codebase is (hopefully) most of the grounding we need. (We'll need to do some work to get memory sharing, but they're still hashing that out in the main project).

**Comment by TheNeuralBit** [comment]
I'm working on a browser-based data visualization tool for large datasets, and I was actually considering switching over to a columnar memory layout like the arrow format to help out with data locality, caching, etc... and eke out a little more performance. I stumbled across the arrow format, and figured if a standard format is emerging I may as well embrace that.

I don' have any problem with C++, as long as I can get my browser to run it :)
I looked into building arrow with emscripten but couldn't get it to work. I think I got as far as building all the dependencies, but couldn't get the actual library to build.

**Pull request merged**
